language: java
jdk:
  - oraclejdk8
install:
  - ./gradlew --version
script:
  - ./gradlew -Dorg.eclipse.concierge.tests.waitAfterFrameworkShutdown=1000 clean build test assembleDist installDist -x signArchives

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
